=== raypendergraph/SemanticScripture/Books/SemanticScripture.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:ss="http://example.com/SemanticScripture"
           targetNamespace="http://example.com/SemanticScripture"
           elementFormDefault="qualified">

    <xs:element name="book" type="ss:BookType"/>

    <xs:complexType name="BookType">
        <xs:sequence>
            <xs:element name="about" type="ss:AboutType"/>
            <xs:element name="chapter" type="ss:ChapterType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="title" type="xs:string" use="required"/>
        <xs:attribute name="n" type="xs:integer" use="optional"/>
    </xs:complexType>

    <xs:complexType name="AboutType">
        <xs:attribute name="title" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="ChapterType">
        <xs:sequence>
            <xs:element name="verse" type="ss:VerseType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="title" type="xs:string" use="required"/>
        <xs:attribute name="n" type="xs:integer" use="required"/>
    </xs:complexType>

    <xs:complexType name="VerseType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="id" type="xs:ID" use="required"/>
                <xs:attribute name="n" type="xs:integer" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

</xs:schema>

=== raypendergraph/SemanticScripture/Books/KJV/Philemon.xml
<?xml version='1.0' encoding='utf-8'?>
<book n="57" title="Philemon" shortName="Phlm" xmlns="http://example.com/SemanticScripture" xsi="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="http://example.com/SemanticScripture SemanticScripture.xsd">
    <chapter n="1">
      <CAPTION vref="1">Written from Rome to Philemon, by Onesimus a servant.</CAPTION>
      <verse n="1" id="phlm.1.1">Paul, a prisoner of Jesus Christ, and Timothy our brother, unto Philemon our dearly beloved, and fellowlabourer,</verse>
      <verse n="2" id="phlm.1.2">And to our beloved Apphia, and Archippus our fellowsoldier, and to the church in thy house:</verse>
      <verse n="3" id="phlm.1.3">Grace to you, and peace, from God our Father and the Lord Jesus Christ.</verse>
      <verse n="4" id="phlm.1.4">I thank my God, making mention of thee always in my prayers,</verse>
      <verse n="5" id="phlm.1.5">Hearing of thy love and faith, which thou hast toward the Lord Jesus, and toward all saints;</verse>
      <verse n="6" id="phlm.1.6">That the communication of thy faith may become effectual by the acknowledging of every good thing which is in you in Christ Jesus.</verse>
      <verse n="7" id="phlm.1.7">For we have great joy and consolation in thy love, because the bowels of the saints are refreshed by thee, brother.</verse>
      <verse n="8" id="phlm.1.8">Wherefore, though I might be much bold in Christ to enjoin thee that which is convenient,</verse>
      <verse n="9" id="phlm.1.9">Yet for love's sake I rather beseech thee, being such an one as Paul the aged, and now also a prisoner of Jesus Christ.</verse>
      <verse n="10" id="phlm.1.10">I beseech thee for my son Onesimus, whom I have begotten in my bonds:</verse>
      <verse n="11" id="phlm.1.11">Which in time past was to thee unprofitable, but now profitable to thee and to me:</verse>
      <verse n="12" id="phlm.1.12">Whom I have sent again: thou therefore receive him, that is, mine own bowels:</verse>
      <verse n="13" id="phlm.1.13">Whom I would have retained with me, that in thy stead he might have ministered unto me in the bonds of the gospel:</verse>
      <verse n="14" id="phlm.1.14">But without thy mind would I do nothing; that thy benefit should not be as it were of necessity, but willingly.</verse>
      <verse n="15" id="phlm.1.15">For perhaps he therefore departed for a season, that thou shouldest receive him for ever;</verse>
      <verse n="16" id="phlm.1.16">Not now as a servant, but above a servant, a brother beloved, specially to me, but how much more unto thee, both in the flesh, and in the Lord?</verse>
      <verse n="17" id="phlm.1.17">If thou count me therefore a partner, receive him as myself.</verse>
      <verse n="18" id="phlm.1.18">If he hath wronged thee, or oweth thee ought, put that on mine account;</verse>
      <verse n="19" id="phlm.1.19">I Paul have written it with mine own hand, I will repay it: albeit I do not say to thee how thou owest unto me even thine own self besides.</verse>
      <verse n="20" id="phlm.1.20">Yea, brother, let me have joy of thee in the Lord: refresh my bowels in the Lord.</verse>
      <verse n="21" id="phlm.1.21">Having confidence in thy obedience I wrote unto thee, knowing that thou wilt also do more than I say.</verse>
      <verse n="22" id="phlm.1.22">But withal prepare me also a lodging: for I trust that through your prayers I shall be given unto you.</verse>
      <verse n="23" id="phlm.1.23">There salute thee Epaphras, my fellowprisoner in Christ Jesus;</verse>
      <verse n="24" id="phlm.1.24">Marcus, Aristarchus, Demas, Lucas, my fellowlabourers.</verse>
      <verse n="25" id="phlm.1.25">The grace of our Lord Jesus Christ be with your spirit. Amen. </verse>
    </chapter>
  </book>

=== raypendergraph/SemanticScripture/Books/KJV/2_Thessalonians.xml
<?xml version='1.0' encoding='utf-8'?>
<book n="53" title="2 Thessalonians" shortName="2Thess" xmlns="http://example.com/SemanticScripture" xsi="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="http://example.com/SemanticScripture SemanticScripture.xsd">
    <chapter n="1">
      <CAPTION vref="1">The second epistle to the Thessalonians was written from Athens.</CAPTION>
      <verse n="1" id="2thess.1.1">Paul, and Silvanus, and Timotheus, unto the church of the Thessalonians in God our Father and the Lord Jesus Christ:</verse>
      <verse n="2" id="2thess.1.2">Grace unto you, and peace, from God our Father and the Lord Jesus Christ.</verse>
      <verse n="3" id="2thess.1.3">We are bound to thank God always for you, brethren, as it is meet, because that your faith groweth exceedingly, and the charity of every one of you all toward each other aboundeth;</verse>
      <verse n="4" id="2thess.1.4">So that we ourselves glory in you in the churches of God for your patience and faith in all your persecutions and tribulations that ye endure:</verse>
      <verse n="5" id="2thess.1.5">Which is a manifest token of the righteous judgment of God, that ye may be counted worthy of the kingdom of God, for which ye also suffer:</verse>
      <verse n="6" id="2thess.1.6">Seeing it is a righteous thing with God to recompense tribulation to them that trouble you;</verse>
      <verse n="7" id="2thess.1.7">And to you who are troubled rest with us, when the Lord Jesus shall be revealed from heaven with his mighty angels,</verse>
      <verse n="8" id="2thess.1.8">In flaming fire taking vengeance on them that know not God, and that obey not the gospel of our Lord Jesus Christ:</verse>
      <verse n="9" id="2thess.1.9">Who shall be punished with everlasting destruction from the presence of the Lord, and from the glory of his power;</verse>
      <verse n="10" id="2thess.1.10">When he shall come to be glorified in his saints, and to be admired in all them that believe (because our testimony among you was believed) in that day.</verse>
      <verse n="11" id="2thess.1.11">Wherefore also we pray always for you, that our God would count you worthy of this calling, and fulfil all the good pleasure of his goodness, and the work of faith with power:</verse>
      <verse n="12" id="2thess.1.12">That the name of our Lord Jesus Christ may be glorified in you, and ye in him, according to the grace of our God and the Lord Jesus Christ.</verse>
    </chapter>
    <chapter n="2">
      <verse n="1" id="2thess.2.1">Now we beseech you, brethren, by the coming of our Lord Jesus Christ, and by our gathering together unto him,</verse>
      <verse n="2" id="2thess.2.2">That ye be not soon shaken in mind, or be troubled, neither by spirit, nor by word, nor by letter as from us, as that the day of Christ is at hand.</verse>
      <verse n="3" id="2thess.2.3">Let no man deceive you by any means: for that day shall not come, except there come a falling away first, and that man of sin be revealed, the son of perdition;</verse>
      <verse n="4" id="2thess.2.4">Who opposeth and exalteth himself above all that is called God, or that is worshipped; so that he as God sitteth in the temple of God, shewing himself that he is God.</verse>
      <verse n="5" id="2thess.2.5">Remember ye not, that, when I was yet with you, I told you these things?</verse>
      <verse n="6" id="2thess.2.6">And now ye know what withholdeth that he might be revealed in his time.</verse>
      <verse n="7" id="2thess.2.7">For the mystery of iniquity doth already work: only he who now letteth will let, until he be taken out of the way.</verse>
      <verse n="8" id="2thess.2.8">And then shall that Wicked be revealed, whom the Lord shall consume with the spirit of his mouth, and shall destroy with the brightness of his coming:</verse>
      <verse n="9" id="2thess.2.9">Even him, whose coming is after the working of Satan with all power and signs and lying wonders,</verse>
      <verse n="10" id="2thess.2.10">And with all deceivableness of unrighteousness in them that perish; because they received not the love of the truth, that they might be saved.</verse>
      <verse n="11" id="2thess.2.11">And for this cause God shall send them strong delusion, that they should believe a lie:</verse>
      <verse n="12" id="2thess.2.12">That they all might be damned who believed not the truth, but had pleasure in unrighteousness.</verse>
      <verse n="13" id="2thess.2.13">But we are bound to give thanks alway to God for you, brethren beloved of the Lord, because God hath from the beginning chosen you to salvation through sanctification of the Spirit and belief of the truth:</verse>
      <verse n="14" id="2thess.2.14">Whereunto he called you by our gospel, to the obtaining of the glory of our Lord Jesus Christ.</verse>
      <verse n="15" id="2thess.2.15">Therefore, brethren, stand fast, and hold the traditions which ye have been taught, whether by word, or our epistle.</verse>
      <verse n="16" id="2thess.2.16">Now our Lord Jesus Christ himself, and God, even our Father, which hath loved us, and hath given us everlasting consolation and good hope through grace,</verse>
      <verse n="17" id="2thess.2.17">Comfort your hearts, and stablish you in every good word and work.</verse>
    </chapter>
    <chapter n="3">
      <verse n="1" id="2thess.3.1">Finally, brethren, pray for us, that the word of the Lord may have free course, and be glorified, even as it is with you:</verse>
      <verse n="2" id="2thess.3.2">And that we may be delivered from unreasonable and wicked men: for all men have not faith.</verse>
      <verse n="3" id="2thess.3.3">But the Lord is faithful, who shall stablish you, and keep you from evil.</verse>
      <verse n="4" id="2thess.3.4">And we have confidence in the Lord touching you, that ye both do and will do the things which we command you.</verse>
      <verse n="5" id="2thess.3.5">And the Lord direct your hearts into the love of God, and into the patient waiting for Christ.</verse>
      <verse n="6" id="2thess.3.6">Now we command you, brethren, in the name of our Lord Jesus Christ, that ye withdraw yourselves from every brother that walketh disorderly, and not after the tradition which he received of us.</verse>
      <verse n="7" id="2thess.3.7">For yourselves know how ye ought to follow us: for we behaved not ourselves disorderly among you;</verse>
      <verse n="8" id="2thess.3.8">Neither did we eat any man's bread for nought; but wrought with labour and travail night and day, that we might not be chargeable to any of you:</verse>
      <verse n="9" id="2thess.3.9">Not because we have not power, but to make ourselves an ensample unto you to follow us.</verse>
      <verse n="10" id="2thess.3.10">For even when we were with you, this we commanded you, that if any would not work, neither should he eat.</verse>
      <verse n="11" id="2thess.3.11">For we hear that there are some which walk among you disorderly, working not at all, but are busybodies.</verse>
      <verse n="12" id="2thess.3.12">Now them that are such we command and exhort by our Lord Jesus Christ, that with quietness they work, and eat their own bread.</verse>
      <verse n="13" id="2thess.3.13">But ye, brethren, be not weary in well doing.</verse>
      <verse n="14" id="2thess.3.14">And if any man obey not our word by this epistle, note that man, and have no company with him, that he may be ashamed.</verse>
      <verse n="15" id="2thess.3.15">Yet count him not as an enemy, but admonish him as a brother.</verse>
      <verse n="16" id="2thess.3.16">Now the Lord of peace himself give you peace always by all means. The Lord be with you all.</verse>
      <verse n="17" id="2thess.3.17">The salutation of Paul with mine own hand, which is the token in every epistle: so I write.</verse>
      <verse n="18" id="2thess.3.18">The grace of our Lord Jesus Christ be with you all. Amen. </verse>
    </chapter>
  </book>
