=== raypendergraph/SemanticScripture/Schema/SemanticScripture.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:ss="http://example.com/SemanticScripture"
           targetNamespace="http://example.com/SemanticScripture"
           elementFormDefault="qualified">

    <xs:element name="text" type="ss:TextType"/>


    <xs:complexType name="AnteType">
        <xs:sequence>
            <xs:element name="caption" type="xs:string" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TextType">
        <xs:sequence>
            <xs:element name="ante" type="ss:AnteType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="sections" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="section" type="ss:SectionType" minOccurs="1" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:integer" use="required"/>
        <xs:attribute name="title" type="xs:string" use="required"/>
        <xs:attribute name="n" type="xs:integer" use="optional"/>
    </xs:complexType>

    <xs:complexType name="AboutType">
        <xs:attribute name="title" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:simpleType name="SectionKind">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ch"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="SectionType">
        <xs:sequence>
            <xs:element name="caption" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="fragments" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="fragment" type="ss:FragmentType" minOccurs="1" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="kind" type="ss:SectionKind" use="required" />
        <xs:attribute name="id" type="xs:integer" use="required"/>
        <xs:attribute name="title" type="xs:string" use="optional"/>
        <xs:attribute name="caption" type="xs:string" use="optional" />
    </xs:complexType>

    <xs:simpleType name="FragmentKind">
        <xs:restriction base="xs:string">
            <xs:enumeration value="vs"/>
            <xs:enumeration value="p"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="FragmentType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="id" type="xs:integer" use="required"/>
                <xs:attribute name="kind" type="ss:FragmentKind" /> 
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== raypendergraph/SemanticScripture/Books/KJV/Jonah.xml
<?xml version='1.0' encoding='utf-8'?>
<text xmlns="http://example.com/SemanticScripture" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" title="Jonah" id="32" xsi:schemaLocation="http://example.com/SemanticScripture ../../Schema/SemanticScripture.xsd">
  <sections>
    <section kind="ch" id="32001">
      <fragments>
        <fragment id="32001001" kind="vs">Now the word of the LORD came unto Jonah the son of Amittai, saying,</fragment>
        <fragment id="32001002" kind="vs">Arise, go to Nineveh, that great city, and cry against it; for their wickedness is come up before me.</fragment>
        <fragment id="32001003" kind="vs">But Jonah rose up to flee unto Tarshish from the presence of the LORD, and went down to Joppa; and he found a ship going to Tarshish: so he paid the fare thereof, and went down into it, to go with them unto Tarshish from the presence of the LORD.</fragment>
        <fragment id="32001004" kind="vs">But the LORD sent out a great wind into the sea, and there was a mighty tempest in the sea, so that the ship was like to be broken.</fragment>
        <fragment id="32001005" kind="vs">Then the mariners were afraid, and cried every man unto his god, and cast forth the wares that were in the ship into the sea, to lighten it of them. But Jonah was gone down into the sides of the ship; and he lay, and was fast asleep.</fragment>
        <fragment id="32001006" kind="vs">So the shipmaster came to him, and said unto him, What meanest thou, O sleeper? arise, call upon thy God, if so be that God will think upon us, that we perish not.</fragment>
        <fragment id="32001007" kind="vs">And they said every one to his fellow, Come, and let us cast lots, that we may know for whose cause this evil is upon us. So they cast lots, and the lot fell upon Jonah.</fragment>
        <fragment id="32001008" kind="vs">Then said they unto him, Tell us, we pray thee, for whose cause this evil is upon us; What is thine occupation? and whence comest thou? what is thy country? and of what people art thou?</fragment>
        <fragment id="32001009" kind="vs">And he said unto them, I am an Hebrew; and I fear the LORD, the God of heaven, which hath made the sea and the dry land.</fragment>
        <fragment id="32001010" kind="vs">Then were the men exceedingly afraid, and said unto him, Why hast thou done this? For the men knew that he fled from the presence of the LORD, because he had told them.</fragment>
        <fragment id="32001011" kind="vs">Then said they unto him, What shall we do unto thee, that the sea may be calm unto us? for the sea wrought, and was tempestuous.</fragment>
        <fragment id="32001012" kind="vs">And he said unto them, Take me up, and cast me forth into the sea; so shall the sea be calm unto you: for I know that for my sake this great tempest is upon you.</fragment>
        <fragment id="32001013" kind="vs">Nevertheless the men rowed hard to bring it to the land; but they could not: for the sea wrought, and was tempestuous against them.</fragment>
        <fragment id="32001014" kind="vs">Wherefore they cried unto the LORD, and said, We beseech thee, O LORD, we beseech thee, let us not perish for this man's life, and lay not upon us innocent blood: for thou, O LORD, hast done as it pleased thee.</fragment>
        <fragment id="32001015" kind="vs">So they took up Jonah, and cast him forth into the sea: and the sea ceased from her raging.</fragment>
        <fragment id="32001016" kind="vs">Then the men feared the LORD exceedingly, and offered a sacrifice unto the LORD, and made vows.</fragment>
        <fragment id="32001017" kind="vs">Now the LORD had prepared a great fish to swallow up Jonah. And Jonah was in the belly of the fish three days and three nights.</fragment>
      </fragments>
    </section>
    <section kind="ch" id="32002">
      <fragments>
        <fragment id="32002001" kind="vs">Then Jonah prayed unto the LORD his God out of the fish's belly,</fragment>
        <fragment id="32002002" kind="vs">And said, I cried by reason of mine affliction unto the LORD, and he heard me; out of the belly of hell cried I, and thou heardest my voice.</fragment>
        <fragment id="32002003" kind="vs">For thou hadst cast me into the deep, in the midst of the seas; and the floods compassed me about: all thy billows and thy waves passed over me.</fragment>
        <fragment id="32002004" kind="vs">Then I said, I am cast out of thy sight; yet I will look again toward thy holy temple.</fragment>
        <fragment id="32002005" kind="vs">The waters compassed me about, even to the soul: the depth closed me round about, the weeds were wrapped about my head.</fragment>
        <fragment id="32002006" kind="vs">I went down to the bottoms of the mountains; the earth with her bars was about me for ever: yet hast thou brought up my life from corruption, O LORD my God.</fragment>
        <fragment id="32002007" kind="vs">When my soul fainted within me I remembered the LORD: and my prayer came in unto thee, into thine holy temple.</fragment>
        <fragment id="32002008" kind="vs">They that observe lying vanities forsake their own mercy.</fragment>
        <fragment id="32002009" kind="vs">But I will sacrifice unto thee with the voice of thanksgiving; I will pay that that I have vowed. Salvation is of the LORD.</fragment>
        <fragment id="32002010" kind="vs">And the LORD spake unto the fish, and it vomited out Jonah upon the dry land.</fragment>
      </fragments>
    </section>
    <section kind="ch" id="32003">
      <fragments>
        <fragment id="32003001" kind="vs">And the word of the LORD came unto Jonah the second time, saying,</fragment>
        <fragment id="32003002" kind="vs">Arise, go unto Nineveh, that great city, and preach unto it the preaching that I bid thee.</fragment>
        <fragment id="32003003" kind="vs">So Jonah arose, and went unto Nineveh, according to the word of the LORD. Now Nineveh was an exceeding great city of three days' journey.</fragment>
        <fragment id="32003004" kind="vs">And Jonah began to enter into the city a day's journey, and he cried, and said, Yet forty days, and Nineveh shall be overthrown.</fragment>
        <fragment id="32003005" kind="vs">So the people of Nineveh believed God, and proclaimed a fast, and put on sackcloth, from the greatest of them even to the least of them.</fragment>
        <fragment id="32003006" kind="vs">For word came unto the king of Nineveh, and he arose from his throne, and he laid his robe from him, and covered him with sackcloth, and sat in ashes.</fragment>
        <fragment id="32003007" kind="vs">And he caused it to be proclaimed and published through Nineveh by the decree of the king and his nobles, saying, Let neither man nor beast, herd nor flock, taste any thing: let them not feed, nor drink water:</fragment>
        <fragment id="32003008" kind="vs">But let man and beast be covered with sackcloth, and cry mightily unto God: yea, let them turn every one from his evil way, and from the violence that is in their hands.</fragment>
        <fragment id="32003009" kind="vs">Who can tell if God will turn and repent, and turn away from his fierce anger, that we perish not?</fragment>
        <fragment id="32003010" kind="vs">And God saw their works, that they turned from their evil way; and God repented of the evil, that he had said that he would do unto them; and he did it not.</fragment>
      </fragments>
    </section>
    <section kind="ch" id="32004">
      <fragments>
        <fragment id="32004001" kind="vs">But it displeased Jonah exceedingly, and he was very angry.</fragment>
        <fragment id="32004002" kind="vs">And he prayed unto the LORD, and said, I pray thee, O LORD, was not this my saying, when I was yet in my country? Therefore I fled before unto Tarshish: for I knew that thou art a gracious God, and merciful, slow to anger, and of great kindness, and repentest thee of the evil.</fragment>
        <fragment id="32004003" kind="vs">Therefore now, O LORD, take, I beseech thee, my life from me; for it is better for me to die than to live.</fragment>
        <fragment id="32004004" kind="vs">Then said the LORD, Doest thou well to be angry?</fragment>
        <fragment id="32004005" kind="vs">So Jonah went out of the city, and sat on the east side of the city, and there made him a booth, and sat under it in the shadow, till he might see what would become of the city.</fragment>
        <fragment id="32004006" kind="vs">And the LORD God prepared a gourd, and made it to come up over Jonah, that it might be a shadow over his head, to deliver him from his grief. So Jonah was exceeding glad of the gourd.</fragment>
        <fragment id="32004007" kind="vs">But God prepared a worm when the morning rose the next day, and it smote the gourd that it withered.</fragment>
        <fragment id="32004008" kind="vs">And it came to pass, when the sun did arise, that God prepared a vehement east wind; and the sun beat upon the head of Jonah, that he fainted, and wished in himself to die, and said, It is better for me to die than to live.</fragment>
        <fragment id="32004009" kind="vs">And God said to Jonah, Doest thou well to be angry for the gourd? And he said, I do well to be angry, even unto death.</fragment>
        <fragment id="32004010" kind="vs">Then said the LORD, Thou hast had pity on the gourd, for the which thou hast not laboured, neither madest it grow; which came up in a night, and perished in a night:</fragment>
        <fragment id="32004011" kind="vs">And should not I spare Nineveh, that great city, wherein are more than sixscore thousand persons that cannot discern between their right hand and their left hand; and also much cattle?</fragment>
      </fragments>
    </section>
  </sections>
</text>

=== raypendergraph/SemanticScripture/Books/KJV/Titus.xml
<?xml version='1.0' encoding='utf-8'?>
<text xmlns="http://example.com/SemanticScripture" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" title="Titus" id="56" xsi:schemaLocation="http://example.com/SemanticScripture ../../Schema/SemanticScripture.xsd">
  <ante>
    <caption>It was written to Titus, ordained the first bishop of the church of the Cretians, from Nicopolis of Macedonia.</caption>
  </ante>
  <sections>
    <section kind="ch" id="56001">
      <fragments>
        <fragment id="56001001" kind="vs">Paul, a servant of God, and an apostle of Jesus Christ, according to the faith of God's elect, and the acknowledging of the truth which is after godliness;</fragment>
        <fragment id="56001002" kind="vs">In hope of eternal life, which God, that cannot lie, promised before the world began;</fragment>
        <fragment id="56001003" kind="vs">But hath in due times manifested his word through preaching, which is committed unto me according to the commandment of God our Saviour;</fragment>
        <fragment id="56001004" kind="vs">To Titus, mine own son after the common faith: Grace, mercy, and peace, from God the Father and the Lord Jesus Christ our Saviour.</fragment>
        <fragment id="56001005" kind="vs">For this cause left I thee in Crete, that thou shouldest set in order the things that are wanting, and ordain elders in every city, as I had appointed thee:</fragment>
        <fragment id="56001006" kind="vs">If any be blameless, the husband of one wife, having faithful children not accused of riot or unruly.</fragment>
        <fragment id="56001007" kind="vs">For a bishop must be blameless, as the steward of God; not selfwilled, not soon angry, not given to wine, no striker, not given to filthy lucre;</fragment>
        <fragment id="56001008" kind="vs">But a lover of hospitality, a lover of good men, sober, just, holy, temperate;</fragment>
        <fragment id="56001009" kind="vs">Holding fast the faithful word as he hath been taught, that he may be able by sound doctrine both to exhort and to convince the gainsayers.</fragment>
        <fragment id="56001010" kind="vs">For there are many unruly and vain talkers and deceivers, specially they of the circumcision:</fragment>
        <fragment id="56001011" kind="vs">Whose mouths must be stopped, who subvert whole houses, teaching things which they ought not, for filthy lucre's sake.</fragment>
        <fragment id="56001012" kind="vs">One of themselves, even a prophet of their own, said, The Cretians are alway liars, evil beasts, slow bellies.</fragment>
        <fragment id="56001013" kind="vs">This witness is true. Wherefore rebuke them sharply, that they may be sound in the faith;</fragment>
        <fragment id="56001014" kind="vs">Not giving heed to Jewish fables, and commandments of men, that turn from the truth.</fragment>
        <fragment id="56001015" kind="vs">Unto the pure all things are pure: but unto them that are defiled and unbelieving is nothing pure; but even their mind and conscience is defiled.</fragment>
        <fragment id="56001016" kind="vs">They profess that they know God; but in works they deny him, being abominable, and disobedient, and unto every good work reprobate.</fragment>
      </fragments>
    </section>
    <section kind="ch" id="56002">
      <fragments>
        <fragment id="56002001" kind="vs">But speak thou the things which become sound doctrine:</fragment>
        <fragment id="56002002" kind="vs">That the aged men be sober, grave, temperate, sound in faith, in charity, in patience.</fragment>
        <fragment id="56002003" kind="vs">The aged women likewise, that they be in behaviour as becometh holiness, not false accusers, not given to much wine, teachers of good things;</fragment>
        <fragment id="56002004" kind="vs">That they may teach the young women to be sober, to love their husbands, to love their children,</fragment>
        <fragment id="56002005" kind="vs">To be discreet, chaste, keepers at home, good, obedient to their own husbands, that the word of God be not blasphemed.</fragment>
        <fragment id="56002006" kind="vs">Young men likewise exhort to be sober minded.</fragment>
        <fragment id="56002007" kind="vs">In all things shewing thyself a pattern of good works: in doctrine shewing uncorruptness, gravity, sincerity,</fragment>
        <fragment id="56002008" kind="vs">Sound speech, that cannot be condemned; that he that is of the contrary part may be ashamed, having no evil thing to say of you.</fragment>
        <fragment id="56002009" kind="vs">Exhort servants to be obedient unto their own masters, and to please them well in all things; not answering again;</fragment>
        <fragment id="56002010" kind="vs">Not purloining, but shewing all good fidelity; that they may adorn the doctrine of God our Saviour in all things.</fragment>
        <fragment id="56002011" kind="vs">For the grace of God that bringeth salvation hath appeared to all men,</fragment>
        <fragment id="56002012" kind="vs">Teaching us that, denying ungodliness and worldly lusts, we should live soberly, righteously, and godly, in this present world;</fragment>
        <fragment id="56002013" kind="vs">Looking for that blessed hope, and the glorious appearing of the great God and our Saviour Jesus Christ;</fragment>
        <fragment id="56002014" kind="vs">Who gave himself for us, that he might redeem us from all iniquity, and purify unto himself a peculiar people, zealous of good works.</fragment>
        <fragment id="56002015" kind="vs">These things speak, and exhort, and rebuke with all authority. Let no man despise thee.</fragment>
      </fragments>
    </section>
    <section kind="ch" id="56003">
      <fragments>
        <fragment id="56003001" kind="vs">Put them in mind to be subject to principalities and powers, to obey magistrates, to be ready to every good work,</fragment>
        <fragment id="56003002" kind="vs">To speak evil of no man, to be no brawlers, but gentle, shewing all meekness unto all men.</fragment>
        <fragment id="56003003" kind="vs">For we ourselves also were sometimes foolish, disobedient, deceived, serving divers lusts and pleasures, living in malice and envy, hateful, and hating one another.</fragment>
        <fragment id="56003004" kind="vs">But after that the kindness and love of God our Saviour toward man appeared,</fragment>
        <fragment id="56003005" kind="vs">Not by works of righteousness which we have done, but according to his mercy he saved us, by the washing of regeneration, and renewing of the Holy Ghost;</fragment>
        <fragment id="56003006" kind="vs">Which he shed on us abundantly through Jesus Christ our Saviour;</fragment>
        <fragment id="56003007" kind="vs">That being justified by his grace, we should be made heirs according to the hope of eternal life.</fragment>
        <fragment id="56003008" kind="vs">This is a faithful saying, and these things I will that thou affirm constantly, that they which have believed in God might be careful to maintain good works. These things are good and profitable unto men.</fragment>
        <fragment id="56003009" kind="vs">But avoid foolish questions, and genealogies, and contentions, and strivings about the law; for they are unprofitable and vain.</fragment>
        <fragment id="56003010" kind="vs">A man that is an heretick after the first and second admonition reject;</fragment>
        <fragment id="56003011" kind="vs">Knowing that he that is such is subverted, and sinneth, being condemned of himself.</fragment>
        <fragment id="56003012" kind="vs">When I shall send Artemas unto thee, or Tychicus, be diligent to come unto me to Nicopolis: for I have determined there to winter.</fragment>
        <fragment id="56003013" kind="vs">Bring Zenas the lawyer and Apollos on their journey diligently, that nothing be wanting unto them.</fragment>
        <fragment id="56003014" kind="vs">And let ours also learn to maintain good works for necessary uses, that they be not unfruitful.</fragment>
        <fragment id="56003015" kind="vs">All that are with me salute thee. Greet them that love us in the faith. Grace be with you all. Amen. </fragment>
      </fragments>
    </section>
  </sections>
</text>

=== raypendergraph/SemanticScripture/Books/KJV/2_John.xml
<?xml version='1.0' encoding='utf-8'?>
<text xmlns="http://example.com/SemanticScripture" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" title="2 John" id="63" xsi:schemaLocation="http://example.com/SemanticScripture ../../Schema/SemanticScripture.xsd">
  <sections>
    <section kind="ch" id="63001">
      <fragments>
        <fragment id="63001001" kind="vs">The elder unto the elect lady and her children, whom I love in the truth; and not I only, but also all they that have known the truth;</fragment>
        <fragment id="63001002" kind="vs">For the truth's sake, which dwelleth in us, and shall be with us for ever.</fragment>
        <fragment id="63001003" kind="vs">Grace be with you, mercy, and peace, from God the Father, and from the Lord Jesus Christ, the Son of the Father, in truth and love.</fragment>
        <fragment id="63001004" kind="vs">I rejoiced greatly that I found of thy children walking in truth, as we have received a commandment from the Father.</fragment>
        <fragment id="63001005" kind="vs">And now I beseech thee, lady, not as though I wrote a new commandment unto thee, but that which we had from the beginning, that we love one another.</fragment>
        <fragment id="63001006" kind="vs">And this is love, that we walk after his commandments. This is the commandment, That, as ye have heard from the beginning, ye should walk in it.</fragment>
        <fragment id="63001007" kind="vs">For many deceivers are entered into the world, who confess not that Jesus Christ is come in the flesh. This is a deceiver and an antichrist.</fragment>
        <fragment id="63001008" kind="vs">Look to yourselves, that we lose not those things which we have wrought, but that we receive a full reward.</fragment>
        <fragment id="63001009" kind="vs">Whosoever transgresseth, and abideth not in the doctrine of Christ, hath not God. He that abideth in the doctrine of Christ, he hath both the Father and the Son.</fragment>
        <fragment id="63001010" kind="vs">If there come any unto you, and bring not this doctrine, receive him not into your house, neither bid him God speed:</fragment>
        <fragment id="63001011" kind="vs">For he that biddeth him God speed is partaker of his evil deeds.</fragment>
        <fragment id="63001012" kind="vs">Having many things to write unto you, I would not write with paper and ink: but I trust to come unto you, and speak face to face, that our joy may be full.</fragment>
        <fragment id="63001013" kind="vs">The children of thy elect sister greet thee. Amen.</fragment>
      </fragments>
    </section>
  </sections>
</text>

=== raypendergraph/SemanticScripture/Books/KJV/Jude.xml
<?xml version='1.0' encoding='utf-8'?>
<text xmlns="http://example.com/SemanticScripture" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" title="Jude" id="65" xsi:schemaLocation="http://example.com/SemanticScripture ../../Schema/SemanticScripture.xsd">
  <sections>
    <section kind="ch" id="65001">
      <fragments>
        <fragment id="65001001" kind="vs">Jude, the servant of Jesus Christ, and brother of James, to them that are sanctified by God the Father, and preserved in Jesus Christ, and called:</fragment>
        <fragment id="65001002" kind="vs">Mercy unto you, and peace, and love, be multiplied.</fragment>
        <fragment id="65001003" kind="vs">Beloved, when I gave all diligence to write unto you of the common salvation, it was needful for me to write unto you, and exhort you that ye should earnestly contend for the faith which was once delivered unto the saints.</fragment>
        <fragment id="65001004" kind="vs">For there are certain men crept in unawares, who were before of old ordained to this condemnation, ungodly men, turning the grace of our God into lasciviousness, and denying the only Lord God, and our Lord Jesus Christ.</fragment>
        <fragment id="65001005" kind="vs">I will therefore put you in remembrance, though ye once knew this, how that the Lord, having saved the people out of the land of Egypt, afterward destroyed them that believed not.</fragment>
        <fragment id="65001006" kind="vs">And the angels which kept not their first estate, but left their own habitation, he hath reserved in everlasting chains under darkness unto the judgment of the great day.</fragment>
        <fragment id="65001007" kind="vs">Even as Sodom and Gomorrha, and the cities about them in like manner, giving themselves over to fornication, and going after strange flesh, are set forth for an example, suffering the vengeance of eternal fire.</fragment>
        <fragment id="65001008" kind="vs">Likewise also these filthy dreamers defile the flesh, despise dominion, and speak evil of dignities.</fragment>
        <fragment id="65001009" kind="vs">Yet Michael the archangel, when contending with the devil he disputed about the body of Moses, durst not bring against him a railing accusation, but said, The Lord rebuke thee.</fragment>
        <fragment id="65001010" kind="vs">But these speak evil of those things which they know not: but what they know naturally, as brute beasts, in those things they corrupt themselves.</fragment>
        <fragment id="65001011" kind="vs">Woe unto them! for they have gone in the way of Cain, and ran greedily after the error of Balaam for reward, and perished in the gainsaying of Core.</fragment>
        <fragment id="65001012" kind="vs">These are spots in your feasts of charity, when they feast with you, feeding themselves without fear: clouds they are without water, carried about of winds; trees whose fruit withereth, without fruit, twice dead, plucked up by the roots;</fragment>
        <fragment id="65001013" kind="vs">Raging waves of the sea, foaming out their own shame; wandering stars, to whom is reserved the blackness of darkness for ever.</fragment>
        <fragment id="65001014" kind="vs">And Enoch also, the seventh from Adam, prophesied of these, saying, Behold, the Lord cometh with ten thousands of his saints,</fragment>
        <fragment id="65001015" kind="vs">To execute judgment upon all, and to convince all that are ungodly among them of all their ungodly deeds which they have ungodly committed, and of all their hard speeches which ungodly sinners have spoken against him.</fragment>
        <fragment id="65001016" kind="vs">These are murmurers, complainers, walking after their own lusts; and their mouth speaketh great swelling words, having men's persons in admiration because of advantage.</fragment>
        <fragment id="65001017" kind="vs">But, beloved, remember ye the words which were spoken before of the apostles of our Lord Jesus Christ;</fragment>
        <fragment id="65001018" kind="vs">How that they told you there should be mockers in the last time, who should walk after their own ungodly lusts.</fragment>
        <fragment id="65001019" kind="vs">These be they who separate themselves, sensual, having not the Spirit.</fragment>
        <fragment id="65001020" kind="vs">But ye, beloved, building up yourselves on your most holy faith, praying in the Holy Ghost,</fragment>
        <fragment id="65001021" kind="vs">Keep yourselves in the love of God, looking for the mercy of our Lord Jesus Christ unto eternal life.</fragment>
        <fragment id="65001022" kind="vs">And of some have compassion, making a difference:</fragment>
        <fragment id="65001023" kind="vs">And others save with fear, pulling them out of the fire; hating even the garment spotted by the flesh.</fragment>
        <fragment id="65001024" kind="vs">Now unto him that is able to keep you from falling, and to present you faultless before the presence of his glory with exceeding joy,</fragment>
        <fragment id="65001025" kind="vs">To the only wise God our Saviour, be glory and majesty, dominion and power, both now and ever. Amen.</fragment>
      </fragments>
    </section>
  </sections>
</text>
